# Generated by Django 4.0.10 on 2024-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_status', models.CharField(max_length=25)),
                ('event_duration', models.DurationField()),
            ],
            options={
                'db_table': 'event_schema"."event',
            },
        ),
    ]
