# Generated by Django 4.0.10 on 2024-04-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_alter_event_event_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
    ]
