# Generated by Django 4.0.10 on 2024-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedataapp', '0005_alter_province_state'),
        ('eventapp', '0004_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_causes',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_causes', to='basedataapp.causes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, default='No Description', null=True),
        ),
    ]
