# Generated by Django 4.0.10 on 2024-03-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedataapp', '0002_initial'),
    ]

    operations = [
    ]
