# Generated by Django 4.0.10 on 2024-03-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedataapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitynature',
            table='basedata_schema"."activitynature',
        ),
    ]
