# Generated by Django 4.0.10 on 2024-03-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedataapp', '0003_remove_work_parent_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='parent_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basedataapp.work'),
        ),
    ]
