# Generated by Django 4.0.10 on 2024-03-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedataapp', '0004_work_parent_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedataapp.state'),
        ),
    ]
