# Generated by Django 4.0.10 on 2024-03-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedataapp', '0004_alter_activitynature_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='installation_id',
            new_name='installation',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_paret',
            new_name='parent_work',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='worktype',
            new_name='work_type',
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('code', 'installation', 'parent_work', 'work_type')},
        ),
    ]
