# Generated by Django 5.0.2 on 2024-02-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userapp', '0002_alter_user_user_company_alter_user_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_group', to='auth.group'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_permissions', to='auth.permission'),
        ),
    ]
