# Generated by Django 4.0.10 on 2024-05-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notification_is_read_remove_notification_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='users',
        ),
    ]
